# Generated by Django 5.2.8 on 2025-11-29 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respaldo',
            options={'permissions': [('can_manage_backups', 'Can manage backups'), ('can_view_audit_logs', 'Can view audit logs')]},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'permissions': [('can_view_reports', 'Can view advanced reports'), ('can_delete_sales', 'Can delete or annul sales')]},
        ),
    ]
