# Generated by Django 5.2.8 on 2025-12-02 20:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercapp', '0006_alter_detalleventa_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Venta'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='respaldo',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'permissions': [('can_manage_backups', 'Can manage backups'), ('can_view_audit_logs', 'Can view audit logs')], 'verbose_name': 'Respaldo', 'verbose_name_plural': 'Respaldos'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-fecha'], 'permissions': [('can_view_reports', 'Can view advanced reports'), ('can_delete_sales', 'Can delete or annul sales')], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='respaldo',
            name='ubicacion',
            field=models.FileField(blank=True, null=True, upload_to='respaldos/'),
        ),
    ]
